### ISSUE TITLE
Missing files for specs

### ISSUE THREAD

**Issue by CardboardMechanic** [LeakyBucket/google_apps#2]
Can't seem to find spec/feed.xml. Looks like the specs expect this to be an example of user profiles with a next link in it. Can you check that in?

Also missing spec/credentials.yaml. I assume this has sensitive data. Maybe you can check in a spec/credentials.example.yaml that shows what the file might look like?

**Comment by LeakyBucket** [comment]
Yeah, sorry about that.  I see you worked around my lack of responsiveness.
